
create table upload_tasklist (
id                   INTEGER                        not null,
create_time          TIMESTAMP,
title                VARCHAR(500),
intro				 VARCHAR(5000),
price                DEC(10,2),
products             VARCHAR(5000),
cover        		 char(250),
images        		 char(500),
old_image        	 char(500),
is_add        	 	 INTEGER,
item_id        	 	 INTEGER,
group_ids			 char(500),
is_only_4_agent      INTEGER,
retail_price         DEC(10,2),
upload_counter 	 	 INTEGER 						default 0,
notified			 INTEGER						default 0,
category			 VARCHAR(100),
styles				 VARCHAR(100),
shop_cats			 VARCHAR(100),
attrs				 VARCHAR(50),
is_top				 INTEGER,
user_id				 INTEGER,
login_user_id		 INTEGER,
item_source_type     INTEGER,
user_name			 VARCHAR(200),
source_id		     INTEGER,
unique_tag			 VARCHAR(200),
primary key (id)
);

create table all_item_list (
id                   INTEGER                        not null,
name                 VARCHAR(500),
intro				 VARCHAR(5000),
username             VARCHAR(200),
create_date          TIMESTAMP,
cover                VARCHAR(250),
price                DEC(10,2),
is_source            INTEGER,
images               char(500),
item_id           	 INTEGER,
item_item_id         INTEGER,
my_id           	 INTEGER,
page_index           INTEGER,
user_id			     INTEGER,
retail_price         DEC(10,2),
org_user_id			 INTEGER,
address				 VARCHAR(500),
backup_address		 VARCHAR(500),
mobile				 VARCHAR(500),
wx_name              VARCHAR(500),
wx_num               VARCHAR(500),
apply_statu_id	     INTEGER,
primary key (id)
);

create table shop_item_list (
id                   INTEGER                        not null,
name                 VARCHAR(500),
intro				 VARCHAR(5000),
username             VARCHAR(200),
create_date          TIMESTAMP,
cover                VARCHAR(250),
price                DEC(10,2),
is_source            INTEGER,
images               char(500),
user_id           	 INTEGER,
item_id           	 INTEGER,
item_item_id         INTEGER,
my_id           	 INTEGER,
page_index           INTEGER,
retail_price         DEC(10,2),
primary key (user_id,page_index,id)
);

create table my_item_list (
id                   INTEGER                        not null,
name                 VARCHAR(500),
intro				 VARCHAR(5000),
username             VARCHAR(200),
create_date          TIMESTAMP,
cover                VARCHAR(250),
price                DEC(10,2),
is_source            INTEGER,
images               char(500),
item_id           	 INTEGER,
item_item_id         INTEGER,
my_id           	 INTEGER,
page_index           INTEGER,
group_ids			 char(500),
group_names		     char(500),
is_only_4_agent      INTEGER,
user_id			     INTEGER,
retail_price         DEC(10,2),
org_user_id			 INTEGER,
address				 VARCHAR(500),
backup_address		 VARCHAR(500),
mobile				 VARCHAR(500),
wx_name              VARCHAR(500),
wx_num               VARCHAR(500),
org_user_name		 VARCHAR(200),
primary key (id)
);


